import React from 'react';
import Head from 'next/head'
import { AddTask, Task } from '../components/index';

export default function Home({ tasksData }) {

  const [tasks, setTasks] = React.useState(tasksData);

  return (
    <div className="bg-light h-screen w-screen">
      <Head>
        <title>MERN Task Manager App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full flex items-center justify-center">
        <div className="w-[60vh] h-[40vh] shadow-xl bg-white rounded-lg font-main text-dark p-4 text-lg">
          <AddTask setTasks={setTasks}/>
          <div className="mt-2 flex flex-col w-full h-full">
            {tasks && tasks.map(task => (
              <Task task={task} setTasks={setTasks}/>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const response = await fetch(`http://localhost:3000/api/getTasks`);
  const tasksData = await response.json();
  
  return {
    props: {
      tasksData
    }
  }
}
